### ISSUE TITLE
FPS is automaticly shown when using cmap

### ISSUE THREAD

**Issue by olepg** [ImberAureus/CMap#1]
Whenever Cmap is active, the FPS counter is activated when I log onto wow.
I've searched the cmap files for mentions of a function like this to manually remove it, but I cant find any.  

But whenever I deactivate cmap, I dont have this issue.

Edit: nevermind.

CMap\Cmap.lua:79
"ToggleFramerate()"  -->   "--ToggleFramerate()"

**Comment by ImberAureus** [comment]
Hey. I'm sorry to say, but the project was never finished and there should still be some debug code in there like that one. Good to know that you managed to solve it though :)
